- name: Set hostname
  hostname:
    name: "{{ hostname }}"

- name: Install Nginx and PHP
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - nginx
    - php-fpm
    - php-mysql
    - php-gd
    - php-zip
    - php8.1
    - php-xml
    - php8.1-curl
    - php8.1-mbstring 

- name: Download Composer.phar
  ansible.builtin.get_url:
    url: "https://getcomposer.org/download/latest-stable/composer.phar"
    dest: "/usr/local/bin/composer"
    mode: "0755"

- name: Install Node.js dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - software-properties-common

- name: Install the gpg key for nodejs LTS
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Install the nodejs LTS repos
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes

- name: Install the nodejs
  apt:
    name: nodejs
    state: present

- name: Create folder for Laravel Starter app
  ansible.builtin.file:
    path: /var/www/laravelsandbox.com/html # nantinya soruce code di simpan di dalam folder `html`
    owner: www-data
    group: www-data
    state: directory
    mode: "0755"

- name: Delete file default config nginx
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop: # loop delete file default config
    - /etc/nginx/sites-available/default
    - /etc/nginx/sites-enabled/default

- name: Copy config nginx from local to server # copy file config `default` yang ada di local dan sudah di buat sesuai kebutuhan.
  ansible.builtin.copy:
    src: files/default
    dest: /etc/nginx/sites-available/default

- name: Symlink sites-availabe to sites-enabled
  ansible.builtin.file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify:
    - Restart nginx

- name: Git config safe directory
  ansible.builtin.shell: git config --global --add safe.directory /var/www/laravelsandbox.com/html

- name: Clone Laravel Starter from Github
  ansible.builtin.git:
    repo: https://github.com/nasirkhan/laravel-starter.git
    dest: /var/www/laravelsandbox.com/html
    force: true

- name: Copy env file
  ansible.builtin.template:
    src: secrets/.env
    dest: /var/www/laravelsandbox.com/html/.env
    backup: false

- name: Change ownership of /var/www/laravelsandbox.com/html/
  become: true
  become_user: root
  command: chown -R www-data:www-data /var/www/laravelsandbox.com/html/