- name: Set hostname
  hostname:
    name: "{{ hostname }}"

- name: Install mariadb
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - mariadb-server
    - mariadb-client
    - python3-mysqldb
    - python3-pip

- name: Update bind address
  ansible.builtin.lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
  notify: 
    - Restart mariadb

- name: Create user DB
  community.mysql.mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: '*.*:ALL,GRANT'
    host: '%'
    state: present
    column_case_sensitive: true

- name: Create database
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    state: present
